# coding: utf-8

"""
    DRKR API

    A sample OpenAPI specification for the DRKR project, covering all endpoint stubs across authentication, users, organizations, deep research items, tags, comments, ratings, research jobs, and search. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import StrictInt, StrictStr, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

from app.schemas._base_model import CustomBaseModel
from app.schemas.api_service import ApiService
class ApiKey(CustomBaseModel):
    """
    ApiKey
    """ # noqa: E501
    id: StrictInt = None
    api_service_id: StrictInt = None
    name: Optional[StrictStr] = None
    user_id: Optional[StrictInt] = None
    organization_id: Optional[StrictInt] = None
    token: Optional[StrictStr] = None
    is_active: Optional[StrictBool] = None
    expires_at: Optional[str] = None
    api_service: Optional[ApiService] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    __properties: ClassVar[List[str]] = ["id", "api_service_id", "name", "user_id", "organization_id", "token", "is_active", "expires_at", "api_service", "created_at", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": False,
        "protected_namespaces": (),
        "from_attributes": True,
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))



