# coding: utf-8

"""
    DRKR API

    A sample OpenAPI specification for the DRKR project, covering all endpoint stubs across authentication, users, organizations, deep research items, tags, comments, ratings, research jobs, and search. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import json

from pydantic import BaseModel, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

from app.schemas._base_model import CustomBaseModel

class OrganizationMember(CustomBaseModel):
    """
    OrganizationMember
    """ # noqa: E501
    id: Optional[StrictInt] = None
    organization_id: Optional[StrictInt] = None
    user_id: Optional[StrictInt] = None
    role: Optional[StrictStr] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    __properties: ClassVar[List[str]] = ["id", "organization_id", "user_id", "role", "created_at", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": False,
        "protected_namespaces": (),
        "from_attributes": True,
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))



