# coding: utf-8

"""
    DRKR API

    A sample OpenAPI specification for the DRKR project, covering all endpoint stubs across authentication, users, organizations, deep research items, tags, comments, ratings, research jobs, and search. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

from app.schemas._base_model import CustomBaseModel

class ResearchJobAnswerRequest(CustomBaseModel):
    """
    ResearchJobAnswerRequest
    """ # noqa: E501
    service: StrictStr
    job_id: StrictStr
    answers: List[StrictStr]
    __properties: ClassVar[List[str]] = ["service", "job_id", "answers"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": False,
        "protected_namespaces": (),
        "json_schema_extra": {
            "example": {
                "service": "open-dr",
                "job_id": "123e4567-e89b-12d3-a456-426614174000",
                "answers": [
                    "Answer to first follow-up question",
                    "Answer to second follow-up question"
                ]
            }
        }
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))
 