# coding: utf-8

"""
    DRKR API

    A sample OpenAPI specification for the DRKR project, covering all endpoint stubs across authentication, users, organizations, deep research items, tags, comments, ratings, research jobs, and search. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from datetime import datetime
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, StrictStr, StrictInt, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

from app.schemas._base_model import CustomBaseModel

class ResearchJob(CustomBaseModel):
    """
    ResearchJob
    """ # noqa: E501
    id: Optional[StrictInt] = None
    job_id: StrictStr
    user_id: int
    owner_user_id: Optional[str] = None
    owner_org_id: Optional[str] = None
    visibility: StrictStr
    status: StrictStr
    service: StrictStr
    prompt: StrictStr
    model_name: StrictStr
    model_params: Optional[Dict[str, Any]] = None
    deep_research_id: Optional[int] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    __properties: ClassVar[List[str]] = ["id", "job_id", "user_id", "owner_user_id", "owner_org_id", "visibility", "status", "service", "model_name", "model_params", "deep_research_id", "created_at", "updated_at"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('pending_answers', 'running', 'completed', 'failed', 'cancelled'):
            raise ValueError("must be one of enum values ('pending_answers', 'running', 'completed', 'failed', 'cancelled')")
        return value

    @field_validator('visibility')
    def visibility_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('private', 'public', 'org'):
            raise ValueError("must be one of enum values ('private', 'public', 'org')")
        return value
    
    @model_validator(mode='before')
    @classmethod
    def validate_datetimes(cls, data: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(data, dict):
            for key, value in data.items():
                if isinstance(value, datetime):
                    data[key] = value.isoformat()
        else:
            if hasattr(data, 'created_at') and isinstance(data.created_at, datetime):
                data.created_at = data.created_at.isoformat()
            if hasattr(data, 'updated_at') and isinstance(data.updated_at, datetime):
                data.updated_at = data.updated_at.isoformat()
        return data

    model_config = {
        "populate_by_name": True,
        "validate_assignment": False,
        "protected_namespaces": (),
        "from_attributes": True,
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))
